os: linux
dist: bionic
language: cpp

services:
  - docker

before_install:
  - docker pull sivertism/fused-dev
  - export BUILDID="build-$RANDOM"
  - >
    docker run
    --name $BUILDID
    -v ${PWD}:/opt/src
    -p 51000:51000
    -d
    -t sivertism/fused-dev:latest

script:
  - >
    docker exec
    -t $BUILDID
    /bin/bash -c "cmake -Bbuild -GNinja"
  - >
    docker exec
    -t $BUILDID
    /bin/bash -c "cmake --build build"
  - >
    docker exec
    -t $BUILDID
    /bin/bash -c "mkdir /tmp/fused-outputs/"
  - >
    docker exec
    -t $BUILDID
    /bin/bash -c "cmake --build build --target testcheck"
